### ISSUE TITLE
create bidding

### ISSUE THREAD

**Issue by adrian27k** [bencevoros/flea-market#10]
-gomb + input mező , mező ellenőrzés mikor rányomunk a licitálás gombra
-item oldalán
-létrehozni egy entitást
-controller meg model réteg extendálás

**Comment by balczarlajos** [comment]
csinosítani lehetne az item oldalát ahol megjelennek a licitek de egyébként már késznek tűnik

**Comment by bencevoros** [comment]
Javítás: [link](https://github.com/bencevoros/flea-market/commit/3519c39e454e8e2e814be83bb92b03595f338751)

* POST / átírva GET /findByItemId, mikor lekérjük a biddeket
* az adatbázisban DATE formátum helyett TIMESTAMP lett, hogy az időt is kezelje
* Bid mentésnél, frissíti az item árát is
* Néhány javitás pl console.log törlés, nemhasznált import törlés stb.
