### ISSUE TITLE
User profile page

### ISSUE THREAD

**Issue by adrian27k** [bencevoros/flea-market#11]
-mindenki nézheti a profilokat
-csak sajátot szerkezthetsz(kivéltel admin)
-hozz létre egy profil oldalt(item mintára)

**Comment by bencevoros** [comment]
A `backend/routes/routes.ts` fájlban, a 14. sor-ban,  `user-page` néven van definiálva a user endpoint. Át kell írni `user`-re, amilyen néven a  `frontend/src/app/services/user.service.ts`-ben is hivjuk.

**Comment by bencevoros** [comment]
A user adataid nem lehet frissíteni. Szerintem jó lenne megcsinálni, hogy lehessen módosítani email-t, illetve jelszavat, úgy hogy megnézi, hogy kéri a jelenlegi jelszót is
