### ISSUE TITLE
Bidding expiration and good boy point collect

### ISSUE THREAD

**Issue by adrian27k** [bencevoros/flea-market#14]
-ha licitál kap, ha terméket visz fel
-egyéb késöbb... #11 #10

**Comment by bencevoros** [comment]
A pontgyűjtés elkezdése előtt, meg kell csinálni, hogy az item-ekre egy adott ideig lehet csak licitálni. Ami szerintem mindenképpen szükséges:
* Kell egy datepicker a frontend-en
* Kell egy új oszlop az adatbázisba az item-ekhez
* Minden bidnél ellenőrizni kell, hogy lejárt-e az item, és ha igen akkor nem lehet érvényes a bid. Ezt frontenden is meg kell jeleniteni egy üzenetben
* Frontenden meg kell jeleníteni, hogy az item lejárt és el kell tünteni a bidding form-ot

**Comment by bencevoros** [comment]
Done with [this commit](https://github.com/bencevoros/flea-market/commit/1c4b2c18cf430c12eba61d17ac115d4f2b7d6bc9)
